# This is the configuration that will be deployed.
#
# If you want to run this relay for local development, make sure to point
# docker-compose to a configuration that has your client's hex key in the
# user_hex_keys array, otherwise the relay will not allow to authenticate
# and send and receive private direct messages.
#
# Until we have a dynamic whitelist for npubs new accounts need to be added
# manually to this file. Most importantly

# local data stored here so this dir needs a persitent volume in GCE.
data_directory = "./data/db"

# within docker we allways want to listen on all addresses
ip_address = "0.0.0.0"

# port can be mapped to any outside port
port = 8080

# this must be the actual domain name from which we access the service
hostname = "bitcr-cloud-run-04-550030097098.europe-west1.run.app"

# I guess this one needs to be true if we have tls enabled via GCE
# locally this fails bcs there is no RealIpHeader present
chorus_is_behind_a_proxy = true

# tls will be provided by GCE ?
use_tls = false

# meta
name = "Bitcredit Relay"
description = "The dev relay for Bitcredit"

# If this is false no unauthenticated users can connect to the relay
# but even if it is true, only users with the hex keys in the user_hex_keys
# array will receive private direct messages.
open_relay = true

# The hex keys of the users that are allowed to connect to the relay and
# send and receive private direct messages.
user_hex_keys = [
  "c0b2884fb510672feceacdb3678b30b157b017bcb06a9fd44642aae18b522aaf", # protom
  "0c9128297e49952a0cf66484904e2e9bfe6482183c36a77f05f4017c487a73c2",
  "87604c05df361aced554a2dcfaaa415d128d43cb820cafca02615b3f6c858fe0",
  "9180c169e5f6d7c579cf1cefa37bffd47a2b389c8125601f4068c87bea795943", # zupzup 1
]

# Do not block ips
enable_ip_blocking = false

# Not sure how this works on subnets so setting this high for dev
max_connections_per_ip = 500
