name: 'Build Docker image'

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  PROJECT_ID: 'cs-host-c9f0ca592f814d028135fa' # TODO: update to your Google Cloud project ID
  GCP_SA_NAME: 'github-actions'
  GAR_LOCATION: 'europe-west1'
  REPOSITORY: 'bitcr-devs-repo'
  IMAGE: 'chorus-relay'

jobs:
  docker_build:
    name: Build image
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    
    # Authenticate Docker to Google Cloud Artifact Registry
    - name: 'Docker Auth'
      uses: 'docker/login-action@v3'
      with:
        username: ${{ env.GCP_SA_NAME }}
        password: '${{ steps.auth.outputs.auth_token }}'
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

    # Build the Docker image
    - name: 'Build and push Docker container'
      run: |-
        DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest"

        docker build \
          --tag "${DOCKER_TAG}" \
          --build-arg GITHUB_SHA="${GITHUB_SHA}" \
          --build-arg GITHUB_REF="${GITHUB_REF}" \
          .

        docker push "${DOCKER_TAG}"