name: Build Docker image

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  IMAGE_TAG: 'europe-west1-docker.pkg.dev/cs-host-c9f0ca592f814d028135fa/bitcr-devs-repo/chorus-relay:latest'
  PROJECT_ID: 'cs-host-c9f0ca592f814d028135fa'
  GAR_LOCATION: 'europe-west1'
  REPOSITORY: 'bitcr-devs-repo'
  IMAGE: 'chorus-relay'
  GCR_INSTANCE: 'bitcr-cloud-run-02'

jobs:
  docker_build:
    name: Build image
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
    
    - name: Docker auth
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

    - name: Build image
      run: docker build --tag ${{ env.IMAGE_TAG }} .
    
    - name: Push image
      run: docker push ${{ env.IMAGE_TAG }}

    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.GCR_INSTANCE }} --image ${{ env.IMAGE_TAG }} --region ${{ env.GAR_LOCATION }} 